export interface LoginResponse {
  ok: boolean;
  token: string;
  user: User;
  errorMsg?: string;
}

export interface User {
  _id: string;
  name: string;
  email: string;
  password: string;
  role: string;
  active: boolean;
}
// Generated by https://quicktype.io

export interface LoginError {
  ok: boolean;
  errorMsg: string;
}
